language: rust
cache: cargo
rust:
  - nightly

env:
  - CURVE=curvesecp256k1
  - CURVE=ed25519
  - CURVE=curveristretto

before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

script:
  - cargo build --verbose --features $CURVE
  - cargo test --verbose --features $CURVE
