[package]
name = "cryptography-utils"
version = "0.1.0"
authors = [
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
rust-gmp = "0.5.0"
rand = "0.4"
ring = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.secp256k1]
version = "0.9.0"
features = ["rand"]
