[package]
name = "cryptography_utils"
version = "0.1.0"
authors = [
    "Gary <gary@kzencorp.com>"
]

[lib]
name = "cryptography_utils"
crate-type = ["dylib"]

[dependencies]
rust-gmp = "0.5.0"
rand = "0.4"
ring = "0.12"

[dependencies.secp256k1]
version = "0.9.0"
features = ["rand"]
