[package]
name = "curv"
version = "0.2.7"
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
zeroize = "0.10"
sha3 = "0.8.2"
sha2 = "0.8.0"
hmac = "0.7.1"
digest = "0.8.1"
hex = "^0.3"
blake2b_simd = "0.5.7"
derivative = "2.1.1"

[dependencies.rust-crypto]
version = "^0.2"

[dependencies.merkle-sha3]
version = "^0.1"


[dependencies.bls12_381]
version = "0.1.1"

[dependencies.sapling-crypto]
git = "https://github.com/omershlo/librustzcash.git"
rev = "3e667406323430813f6dbae2a60b5a83046fa20a"

[dependencies.pairing]
git = "https://github.com/omershlo/librustzcash.git"
rev = "3e667406323430813f6dbae2a60b5a83046fa20a"

[dependencies.rust-gmp]
version = "0.5.0"
features = ["serde_support"]
git = "https://github.com/KZen-networks/rust-gmp"

[dependencies.secp256k1]
version = "0.15.3"
features = ["serde"]

[dependencies.curve25519-dalek]
version = "1.2.3"

[dependencies.cryptoxide]
version = "0.1.2"

[dependencies.p256]
version = "0.5"
features = ["ecdsa"]

[dependencies.generic-array]
version = "0.14"

[dev-dependencies]
bincode = "1.1"
serde_json = "1.0"
paste = "1.0.2"
