[package]
name = "cryptography-utils"
version = "0.1.0"
authors = [
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[features]
curvesecp256k1 = []
curve25519 = []


[dependencies]
rand = "0.5"
ring = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
merkle = "1.10.0"

[dependencies.rust-gmp]
version = "0.5.0"
features = ["serde_support"]
git = "https://github.com/KZen-networks/rust-gmp"

[dependencies.secp256k1]
version = "0.11.1"
features = ["rand", "serde"]

[dependencies.curve25519-dalek]
version = "0.19.0"
