[package]
name = "curv"
version = "0.1.0"


[lib]
crate-type = ["lib"]

[features]
curvesecp256k1 = []
curveristretto = []
ed25519 = []
curvejubjub = []


[dependencies]
rand = "0.6"
ring = "0.13.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
merkle = "1.10.0"
zeroize = "0.5.2"
sha3 = "0.8.1"

[dependencies.sapling-crypto]
git = "https://github.com/zcash/librustzcash.git"
rev = "06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5"

[dependencies.pairing]
git = "https://github.com/zcash/librustzcash.git"
rev = "06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5"

[dependencies.rust-gmp]
version = "0.5.0"
features = ["serde_support"]
git = "https://github.com/KZen-networks/rust-gmp"

[dependencies.secp256k1]
version = "0.12.0"
features = ["rand", "serde"]

[dependencies.curve25519-dalek]
version = "1.0.1"

[dependencies.cryptoxide]
version = "0.1.0"

