[package]
name = "curv"
version = "0.1.0"


[lib]
crate-type = ["lib"]

[features]
default = ["rust-gmp"]
ec_secp256k1 = ["rust-gmp" ,"ecc", "secp256k1"]
ec_ristretto = ["rust-gmp", "ecc" , "curve25519-dalek"]
ec_ed25519 = ["rust-gmp", "ecc" , "cryptoxide"]
ec_jubjub = ["rust-gmp", "ecc" , "pairing", "sapling-crypto"]
ecc = []

[dependencies]
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
zeroize = "0.5.2"
sha3 = "0.8.1"
rust-crypto = "^0.2"
hex = "^0.3"
merkle-sha3 = "^0.1"
blake2b_simd = "0.5.6"

#[dependencies.sapling-crypto]
#git = "https://github.com/zcash/librustzcash.git"
#rev = "06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5"

#[dependencies.pairing]
#git = "https://github.com/zcash/librustzcash.git"
#rev = "06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5"

[dependencies.sapling-crypto]
git = "https://github.com/omershlo/librustzcash.git"
rev = "3e667406323430813f6dbae2a60b5a83046fa20a"
optional = true

[dependencies.pairing]
git = "https://github.com/omershlo/librustzcash.git"
rev = "3e667406323430813f6dbae2a60b5a83046fa20a"
optional = true


[dependencies.rust-gmp]
version = "0.5.0"
features = ["serde_support"]
git = "https://github.com/KZen-networks/rust-gmp"
optional = true

[dependencies.secp256k1]
version = "0.14.0"
features = ["serde"]
optional = true

[dependencies.curve25519-dalek]
version = "1.0.1"
optional = true

[dependencies.cryptoxide]
version = "0.1.0"
optional = true


[dev-dependencies]
serde_json = "1.0"

